GET http://localhost:3001/api/blogs

###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title":"Trial blog ",
     "author":"Moi",
     "url":"<Insert Random URL here>",
     "likes":100
}